#!/bin/sh

# This is the example configuration file for river.
#
# If you wish to edit this, you will probably want to copy it to
# $XDG_CONFIG_HOME/river/init or $HOME/.config/river/init first.
#
# See the river(1), riverctl(1), and rivertile(1) man pages for complete
# documentation.

mod='Mod4'

riverctl map normal $mod Return spawn foot

# $mod+Q to close the focused view
riverctl map normal $mod Q close

riverctl map normal $mod W spawn firefox
riverctl map normal $mod+Shift B spawn bleachbit
riverctl map normal $mod g spawn gimp
riverctl map normal $mod+Shift N spawn 'foot -e newsboat'
riverctl map normal $mod Escape spawn 'foot -e htop'
riverctl map normal $mod N spawn 'foot -e nvim'
riverctl map normal $mod I spawn 'foot -e lf'
riverctl map normal $mod P spawn 'foot -e pulsemixer'
riverctl map normal $mod+Shift W spawn 'foot -e nmtui'
riverctl map normal Shift+Mod1 L spawn 'waylock -init-color 0x1e1e2e -input-color 0x89b4fa -fail-color 0xf38ba8 -ignore-empty-password'

# riverctl map normal $mod D spawn 'tofi-drun --drun-launch=true'
riverctl map normal $mod D spawn '~/.local/bin/fuzzel.sh'
riverctl map normal $mod O spawn '~/.local/bin/snippet.sh'
riverctl map normal $mod+Shift O spawn '~/.local/bin/key.sh'
riverctl map normal $mod+Shift F spawn '~/.local/bin/grim.sh'

riverctl map normal $mod Backspace spawn 'sh -c "pkill -SIGKILL wf-recorder; pkill ffmpeg"'

riverctl map normal Mod1+Shift D spawn 'foot -e sudo poweroff -i'
riverctl map normal Mod1+Shift R spawn 'foot -e sudo reboot -i'

riverctl map normal XKB_KEY_F12 spawn 'wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%+'
riverctl map normal XKB_KEY_F11 spawn 'wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-'
riverctl map normal XKB_KEY_F10 spawn 'wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle'
riverctl map normal XKB_KEY_F9 spawn 'wpctl set-volume @DEFAULT_AUDIO_SINK@ 0%'

riverctl map normal Mod1 P spawn 'brightnessctl set 5%+'
riverctl map normal Mod1 L spawn 'brightnessctl set 5%-'

# $mod+Shift+E to exit river
riverctl map normal $mod+Shift Q exit

# $mod+J and $mod+K to focus the next/previous view in the layout stack
riverctl map normal $mod J focus-view next
riverctl map normal $mod K focus-view previous

# $mod+Shift+J and $mod+Shift+K to swap the focused view with the next/previous
# view in the layout stack
riverctl map normal $mod+Shift J swap next
riverctl map normal $mod+Shift K swap previous

# $mod+Period and $mod+Comma to focus the next/previous output
riverctl map normal $mod Period focus-output next
riverctl map normal $mod Comma focus-output previous

# $mod+Shift+{Period,Comma} to send the focused view to the next/previous output
riverctl map normal $mod+Shift Period send-to-output next
riverctl map normal $mod+Shift Comma send-to-output previous

# $mod+Return to bump the focused view to the top of the layout stack
riverctl map normal $mod Space zoom

# $mod+H and $mod+L to decrease/increase the main ratio of rivertile(1)
riverctl map normal $mod H send-layout-cmd rivertile 'main-ratio -0.05'
riverctl map normal $mod L send-layout-cmd rivertile 'main-ratio +0.05'

# $mod+Shift+H and $mod+Shift+L to increment/decrement the main count of rivertile(1)
riverctl map normal $mod+Shift H send-layout-cmd rivertile 'main-count +1'
riverctl map normal $mod+Shift L send-layout-cmd rivertile 'main-count -1'

# $mod+Mod1+{H,J,K,L} to move views
riverctl map normal $mod+Mod1 H move left 100
riverctl map normal $mod+Mod1 J move down 100
riverctl map normal $mod+Mod1 K move up 100
riverctl map normal $mod+Mod1 L move right 100

# $mod+Mod1+Control+{H,J,K,L} to snap views to screen edges
riverctl map normal $mod+Mod1+Control H snap left
riverctl map normal $mod+Mod1+Control J snap down
riverctl map normal $mod+Mod1+Control K snap up
riverctl map normal $mod+Mod1+Control L snap right

# $mod+Mod1+Shift+{H,J,K,L} to resize views
riverctl map normal $mod+Mod1+Shift H resize horizontal -100
riverctl map normal $mod+Mod1+Shift J resize vertical 100
riverctl map normal $mod+Mod1+Shift K resize vertical -100
riverctl map normal $mod+Mod1+Shift L resize horizontal 100

# $mod + Left Mouse Button to move views
riverctl map-pointer normal $mod BTN_LEFT move-view

# $mod + Right Mouse Button to resize views
riverctl map-pointer normal $mod BTN_RIGHT resize-view

# $mod + Middle Mouse Button to toggle float
riverctl map-pointer normal $mod BTN_MIDDLE toggle-float

for i in $(seq 1 9)
do
    tags=$((1 << ($i - 1)))

    # $mod+[1-9] to focus tag [0-8]
    riverctl map normal $mod $i set-focused-tags $tags

    # $mod+Shift+[1-9] to tag focused view with tag [0-8]
    riverctl map normal $mod+Shift $i set-view-tags $tags

    # $mod+Control+[1-9] to toggle focus of tag [0-8]
    riverctl map normal $mod+Control $i toggle-focused-tags $tags

    # $mod+Shift+Control+[1-9] to toggle tag [0-8] of focused view
    riverctl map normal $mod+Shift+Control $i toggle-view-tags $tags
done

# $mod+0 to focus all tags
# $mod+Shift+0 to tag focused view with all tags
all_tags=$(((1 << 32) - 1))
riverctl map normal $mod 0 set-focused-tags $all_tags
riverctl map normal $mod+Shift 0 set-view-tags $all_tags
riverctl map normal $mod Tab focus-previous-tags
riverctl map normal $mod+Mod1 Tab send-to-previous-tags

# $mod+Space to toggle float
riverctl map normal $mod R toggle-float

# $mod+F to toggle fullscreen
riverctl map normal $mod F toggle-fullscreen

# $mod+{Up,Right,Down,Left} to change layout orientation
riverctl map normal $mod Up    send-layout-cmd rivertile 'main-location top'
riverctl map normal $mod Right send-layout-cmd rivertile 'main-location right'
riverctl map normal $mod Down  send-layout-cmd rivertile 'main-location bottom'
riverctl map normal $mod Left  send-layout-cmd rivertile 'main-location left'

# Declare a passthrough mode. This mode has only a single mapping to return to
# normal mode. This makes it useful for testing a nested wayland compositor
# riverctl declare-mode passthrough

# $mod+F11 to enter passthrough mode
# riverctl map normal $mod F11 enter-mode passthrough

# $mod+F11 to return to normal mode
# riverctl map passthrough $mod F11 enter-mode normal

# Various media key mapping examples for both normal and locked mode which do
# not have a modifier
for mode in normal locked
do

    # Eject the optical drive (well if you still have one that is)
    riverctl map $mode None XF86Eject spawn 'eject -T'

    riverctl map $mode None XF86AudioRaiseVolume  spawn 'wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%+'
    riverctl map $mode None XF86AudioLowerVolume  spawn 'wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-'
    riverctl map $mode None XF86AudioMute         spawn 'wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle'

    riverctl map $mode None XF86AudioMedia spawn 'playerctl play-pause'
    riverctl map $mode None XF86AudioPlay  spawn 'playerctl play-pause'
    riverctl map $mode None XF86AudioPrev  spawn 'playerctl previous'
    riverctl map $mode None XF86AudioNext  spawn 'playerctl next'

    riverctl map $mode None XF86MonBrightnessUp   spawn 'brightnessctl set +5%'
    riverctl map $mode None XF86MonBrightnessDown spawn 'brightnessctl set 5%-'

done

# Set background and border color
riverctl background-color 0x11111b
riverctl border-color-focused 0x93a1a1
riverctl border-color-unfocused 0x586e75

# Set keyboard repeat rate
riverctl keyboard-layout -options 'compose:rMod1' us
riverctl set-repeat 50 300

# Make all views with an app-id that starts with "float" and title "foo" start floating.
riverctl rule-add -app-id 'float*' -title 'foo' float

# Make all views with app-id "bar" and any title use client-side decorations
riverctl rule-add -app-id 'bar' csd

# Cursor Specefic
riverctl hide-cursor timeout 5000
riverctl hide-cursor when-typing enabled
# riverctl xcursor-theme Adwaita 24

# Custom rules
riverctl rule-add -app-id 'imv*' float
riverctl rule-add -app-id 'mpv*' float
# riverctl rule-add -app-id foot -title 'htop' float
# riverctl close-view -title 'htop'

# Set the default layout generator to be rivertile and start it.
# River will send the process group of the init executable SIGTERM on exit.
riverctl default-layout rivertile

# Swap capslock and escape
riverctl keyboard-layout -options 'caps:swapescape' us

rivertile -view-padding 6 -outer-padding 6 &
foot --server &
swaybg -i ~/.local/share/wall/3.png &
waybar &
