initial-color-theme=light
pad=5x0 center
#term=xterm-256color
#term=foot-direct
title=Terminal
app-id=terminal
font=monospace:size=12
# line-height=24
vertical-letter-offset=0
dpi-aware=no
selection-target=both
# initial-window-size-chars=100x30
#notify-focus-inhibit=no

[desktop-notifications]
inhibit-when-focused=no

[scrollback]
indicator-position=relative
indicator-format=percentage

[bell]
urgent=yes

[mouse]
hide-when-typing=no

[key-bindings]
#scrollback-up-page=Mod1+Shift+K
#scrollback-down-page=Mod1+Shift+J
font-reset=Mod1+Shift+0
font-increase=Mod1+Shift+k
font-decrease=Mod1+Shift+j
clipboard-paste=Mod1+v
clipboard-copy=Mod1+c
#primary-paste=Mod1+p
#show-urls-launch=Mod1+u
#show-urls-copy=Mod1+Shift+u
search-start=Mod1+s

[url]
launch=xdg-open ${url}

[csd]
border-width=3

[tweak]
delayed-render-lower=0
delayed-render-upper=1

[colors-light]
background=ffffff
foreground=000000
regular0=000000
regular1=a60000
regular2=006800
regular3=6f5500
regular4=0031a9
regular5=721045
regular6=005e8b
regular7=9f9f9f
bright0=595959
bright1=d00000
bright2=008900
bright3=808000
bright4=0000ff
bright5=dd22dd
bright6=008899
bright7=c4c4c4
